-- CreateEnum
CREATE TYPE "DocumentType" AS ENUM ('ID_CARD', 'UNIVERSITY_CARD', 'ACADEMIC_CERTIFICATE', 'PASSPORT', 'HIGH_DIPLOMA_CERTIFICATE', 'BA_CERTIFICATE', 'PHD_CERTIFICATE', 'DATE_OF_BIRTH', 'TRANSCRIPT', 'RECOMMENDATION_LETTER', 'MOTIVATION_LETTER', 'CV', 'TEACHING_CERTIFICATE', 'RESEARCH_PUBLICATION', 'PDF_FILE', 'OTHER');

-- AlterTable
ALTER TABLE "ProfessorProfile" ADD COLUMN     "documents" TEXT[];

-- AlterTable
ALTER TABLE "StudentProfile" ADD COLUMN     "documents" TEXT[];
